# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-27 01:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login_app', '0002_auto_20171026_1029'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='name',
            new_name='first_name',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='alias',
            new_name='last_name',
        ),
    ]
