# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-27 15:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home_app', '0003_item_desc'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ItemManager',
        ),
    ]
